name: DKN L2 Oracle Dev Image (GPT)
on:
  push:
    branches: ["master"]

jobs:
  build-and-push:
    name: Build and Push GPT Dev Image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: "false"

      - name: Login to ECR
        uses: docker/login-action@v3
        with:
          registry: 974464413599.dkr.ecr.us-east-1.amazonaws.com

      - name: Get Unix Time
        id: timestamp
        run: echo "timestamp=$(date +%s)" >> $GITHUB_OUTPUT

      - name: Get SHA
        id: sha
        run: echo "sha=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Get Branch Name
        id: branch
        run: echo "branch=$(echo ${GITHUB_REF#refs/heads/})" >> $GITHUB_OUTPUT

      - name: Set Image Tag
        id: itag
        run: echo "itag=${{ steps.branch.outputs.branch }}-${{ steps.sha.outputs.sha }}-${{ steps.timestamp.outputs.timestamp }}" >> $GITHUB_OUTPUT

      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          IMAGE_TAG: ${{ steps.itag.outputs.itag }}
        with:
          target: gpt
          platforms: linux/amd64
          push: true
          tags: |
            974464413599.dkr.ecr.us-east-1.amazonaws.com/dkn-l2-oracle-gpt:dev
            974464413599.dkr.ecr.us-east-1.amazonaws.com/dkn-l2-oracle-gpt:${{ env.IMAGE_TAG }}
